"""Read-only investigation contracts and deterministic trigger rules."""

from .agent import (
    InvestigationAgentFinding,
    InvestigationAgentOutput,
    InvestigationAgentRelatedEntity,
    InvestigationAgentService,
    InvestigationAgentStatus,
)
from .artifacts import load_investigation_artifacts, save_investigation_artifacts
from .comparison import (
    ComparisonRunOutcome,
    ConditionalRate,
    EvaluationCase,
    ModelComparisonSummary,
    ModelFacingContextSummary,
    ToolPayloadBytes,
    score_comparison_run,
    summarize_model_comparison,
)
from .errors import GroundingFailureCode, InvestigationGroundingError
from .grounding import validate_report_grounding
from .ledger import (
    EvidenceLedger,
    EvidenceLedgerSnapshot,
    InvestigationExecution,
    InvestigationToolTrace,
    ModelFacingContextMetrics,
    ModelFacingToolCallMetrics,
    model_facing_context_metrics,
    model_facing_tool_call_metrics,
)
from .models import (
    EvidenceFinding,
    EvidenceItem,
    EvidenceSource,
    EvidenceType,
    GroundingFailureDiagnostic,
    InvestigationConfig,
    InvestigationPattern,
    InvestigationReport,
    InvestigationRequest,
    InvestigationStatus,
    InvestigationSubjectType,
    InvestigationTrigger,
    InvestigationTriggerConfig,
    InvestigationTriggerReason,
    InvestigationUsage,
    ReasoningEffort,
    RelatedEntity,
)
from .provenance import (
    AGENT_PROMPT_CONTRACT_VERSION,
    DIAGNOSTIC_PROVENANCE_CONTRACT_VERSION,
    EVIDENCE_CONTRACT_VERSION,
    INVESTIGATION_PROVENANCE_CONTRACT_VERSION,
    REPORT_PROVENANCE_CONTRACT_VERSION,
    diagnostic_id,
    evidence_id,
    investigation_id,
    investigation_provenance,
    report_id,
)
from .service import EvidenceService
from .tools import (
    INVESTIGATION_TOOL_NAMES,
    InvestigationToolBudget,
    InvestigationToolBudgetExhausted,
    InvestigationToolContext,
    build_investigation_tools,
)
from .triggers import should_investigate

__all__ = [
    "AGENT_PROMPT_CONTRACT_VERSION",
    "DIAGNOSTIC_PROVENANCE_CONTRACT_VERSION",
    "EVIDENCE_CONTRACT_VERSION",
    "INVESTIGATION_PROVENANCE_CONTRACT_VERSION",
    "INVESTIGATION_TOOL_NAMES",
    "REPORT_PROVENANCE_CONTRACT_VERSION",
    "ComparisonRunOutcome",
    "ConditionalRate",
    "EvaluationCase",
    "EvidenceFinding",
    "EvidenceItem",
    "EvidenceLedger",
    "EvidenceLedgerSnapshot",
    "EvidenceService",
    "EvidenceSource",
    "EvidenceType",
    "GroundingFailureCode",
    "GroundingFailureDiagnostic",
    "InvestigationAgentFinding",
    "InvestigationAgentOutput",
    "InvestigationAgentRelatedEntity",
    "InvestigationAgentService",
    "InvestigationAgentStatus",
    "InvestigationConfig",
    "InvestigationExecution",
    "InvestigationGroundingError",
    "InvestigationPattern",
    "InvestigationReport",
    "InvestigationRequest",
    "InvestigationStatus",
    "InvestigationSubjectType",
    "InvestigationToolBudget",
    "InvestigationToolBudgetExhausted",
    "InvestigationToolContext",
    "InvestigationToolTrace",
    "InvestigationTrigger",
    "InvestigationTriggerConfig",
    "InvestigationTriggerReason",
    "InvestigationUsage",
    "ModelComparisonSummary",
    "ModelFacingContextMetrics",
    "ModelFacingContextSummary",
    "ModelFacingToolCallMetrics",
    "ReasoningEffort",
    "RelatedEntity",
    "ToolPayloadBytes",
    "build_investigation_tools",
    "diagnostic_id",
    "evidence_id",
    "investigation_id",
    "investigation_provenance",
    "load_investigation_artifacts",
    "model_facing_context_metrics",
    "model_facing_tool_call_metrics",
    "report_id",
    "save_investigation_artifacts",
    "score_comparison_run",
    "should_investigate",
    "summarize_model_comparison",
    "validate_report_grounding",
]
