"""persist operational runtime lineage

Revision ID: c263e0cacd3d
Revises:
Create Date: 2026-08-29 12:55:44.519706
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c263e0cacd3d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "score_observations",
        sa.Column("score_id", sa.String(length=64), nullable=False),
        sa.Column("base_model_id", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("scoring_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_vector_id", sa.String(length=64), nullable=False),
        sa.Column("raw_model_score", sa.Float(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("score_id", name=op.f("pk_score_observations")),
    )
    op.create_index(
        "ix_score_observations_subject_id_scoring_cutoff",
        "score_observations",
        ["subject_id", "scoring_cutoff"],
        unique=False,
    )
    op.create_table(
        "probability_estimates",
        sa.Column("probability_estimate_id", sa.String(length=64), nullable=False),
        sa.Column("score_id", sa.String(length=64), nullable=False),
        sa.Column("base_model_id", sa.String(length=64), nullable=False),
        sa.Column("probability_model_id", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("feature_vector_id", sa.String(length=64), nullable=False),
        sa.Column("scoring_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calibrated_probability", sa.Float(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["score_observations.score_id"],
            name=op.f("fk_probability_estimates_score_id_score_observations"),
        ),
        sa.PrimaryKeyConstraint(
            "probability_estimate_id", name=op.f("pk_probability_estimates")
        ),
    )
    op.create_index(
        "ix_probability_estimates_subject_id_scoring_cutoff",
        "probability_estimates",
        ["subject_id", "scoring_cutoff"],
        unique=False,
    )
    op.create_table(
        "policy_decisions",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("probability_estimate_id", sa.String(length=64), nullable=False),
        sa.Column("score_id", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("base_model_id", sa.String(length=64), nullable=False),
        sa.Column("probability_model_id", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("feature_vector_id", sa.String(length=64), nullable=False),
        sa.Column("scoring_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context_id", sa.String(length=255), nullable=True),
        sa.Column("chosen_action", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["probability_estimate_id"],
            ["probability_estimates.probability_estimate_id"],
            name=op.f(
                "fk_policy_decisions_probability_estimate_id_probability_estimates"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["score_observations.score_id"],
            name=op.f("fk_policy_decisions_score_id_score_observations"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_policy_decisions")),
    )
    op.create_index(
        "ix_policy_decisions_context_id",
        "policy_decisions",
        ["context_id"],
        unique=False,
    )
    op.create_index(
        "ix_policy_decisions_subject_id_scoring_cutoff",
        "policy_decisions",
        ["subject_id", "scoring_cutoff"],
        unique=False,
    )
    op.create_table(
        "investigation_requests",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("probability_estimate_id", sa.String(length=64), nullable=False),
        sa.Column("score_id", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=False),
        sa.Column("cutoff_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context_id", sa.String(length=255), nullable=True),
        sa.Column("policy_action", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["policy_decisions.decision_id"],
            name=op.f("fk_investigation_requests_decision_id_policy_decisions"),
        ),
        sa.ForeignKeyConstraint(
            ["probability_estimate_id"],
            ["probability_estimates.probability_estimate_id"],
            name=op.f(
                "fk_investigation_requests_probability_estimate_id_probability_estimates"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["score_observations.score_id"],
            name=op.f("fk_investigation_requests_score_id_score_observations"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_investigation_requests")),
    )
    op.create_index(
        "ix_investigation_requests_subject_id_cutoff_time",
        "investigation_requests",
        ["subject_id", "cutoff_time"],
        unique=False,
    )
    op.create_table(
        "investigation_reports",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("policy_action", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("pattern", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["investigation_requests.decision_id"],
            name=op.f("fk_investigation_reports_decision_id_investigation_requests"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_investigation_reports")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("investigation_reports")
    op.drop_index(
        "ix_investigation_requests_subject_id_cutoff_time",
        table_name="investigation_requests",
    )
    op.drop_table("investigation_requests")
    op.drop_index(
        "ix_policy_decisions_subject_id_scoring_cutoff", table_name="policy_decisions"
    )
    op.drop_index("ix_policy_decisions_context_id", table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(
        "ix_probability_estimates_subject_id_scoring_cutoff",
        table_name="probability_estimates",
    )
    op.drop_table("probability_estimates")
    op.drop_index(
        "ix_score_observations_subject_id_scoring_cutoff",
        table_name="score_observations",
    )
    op.drop_table("score_observations")
    # ### end Alembic commands ###
