"""Synchronous SQLAlchemy foundation for Mayajaal operational storage."""

from .base import Base
from .config import DATABASE_URL_ENVIRONMENT_VARIABLE, DatabaseConfig
from .engine import DatabaseRuntime, create_database_runtime, ping_database
from .models import (
    FeatureVectorRecord,
    InvestigationReportRecord,
    InvestigationRequestRecord,
    InvestigationRunRecord,
    NormalizedEventRecord,
    PolicyDecisionRecord,
    ProbabilityEstimateRecord,
    RiskCaseDecisionRecord,
    RiskCaseRecord,
    RiskEvaluationRecord,
    RiskProcessingFailureRecord,
    ScoreObservationRecord,
    WebhookEventRecord,
)
from .repositories import (
    FeatureVectorRepository,
    ImmutablePersistenceConflict,
    InvestigationReportRepository,
    InvestigationRequestRepository,
    InvestigationRunRepository,
    NormalizedEventRepository,
    PolicyDecisionRepository,
    ProbabilityEstimateRepository,
    RiskCaseRepository,
    RiskEvaluationRepository,
    RiskProcessingFailureRepository,
    ScoreObservationRepository,
    WebhookClaimUnavailable,
    WebhookEventRepository,
    WebhookPayloadConflict,
)
from .session import SessionFactory, session_scope

__all__ = [
    "DATABASE_URL_ENVIRONMENT_VARIABLE",
    "Base",
    "DatabaseConfig",
    "DatabaseRuntime",
    "FeatureVectorRecord",
    "FeatureVectorRepository",
    "ImmutablePersistenceConflict",
    "InvestigationReportRecord",
    "InvestigationReportRepository",
    "InvestigationRequestRecord",
    "InvestigationRequestRepository",
    "InvestigationRunRecord",
    "InvestigationRunRepository",
    "NormalizedEventRecord",
    "NormalizedEventRepository",
    "PolicyDecisionRecord",
    "PolicyDecisionRepository",
    "ProbabilityEstimateRecord",
    "ProbabilityEstimateRepository",
    "RiskCaseDecisionRecord",
    "RiskCaseRecord",
    "RiskCaseRepository",
    "RiskEvaluationRecord",
    "RiskEvaluationRepository",
    "RiskProcessingFailureRecord",
    "RiskProcessingFailureRepository",
    "ScoreObservationRecord",
    "ScoreObservationRepository",
    "SessionFactory",
    "WebhookClaimUnavailable",
    "WebhookEventRecord",
    "WebhookEventRepository",
    "WebhookPayloadConflict",
    "create_database_runtime",
    "ping_database",
    "session_scope",
]
